export const ROUTE_TITLES: Record<string, string> = {
  "/": "Ireland's Leading Financial Advisor",
  "/about": "About Us",
  "/about/team": "Our Team",
  "/about/testimonials": "Testimonials",
  "/about/charges": "Charges",
  "/contact": "Contact Us",
  "/financial-planning": "Financial Planning Benefits",
  "/financial-planning/step-by-step": "Step-by-Step Process",
  "/financial-planning/benefits": "Benefits of a Good Financial Plan",
  "/financial-planning/ethics": "IFC Finance Ethics",
  "/personal": "Personal Financial Planning",
  "/company": "Company-Led Financial Planning",
  "/group-risk": "Group Risk",
  "/invoice-finance": "Invoice Finance",
  "/blog": "Blog",
  "/calculators/ip-calc": "IP Calculator",
  "/privacy": "Privacy Policy",
};
